
[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "0.9.0"

[[constraint]]
  branch = "ktsanaktsidis/no_splay_on_kill"
  name = "github.com/hashicorp/consul-template"
  source = "https://github.com/zendesk/consul-template"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-gatedio"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
